### ISSUE TITLE
[MP] Summoning witch could move and summon twice 

### ISSUE THREAD

**Issue by calmackenzie** [calmackenzie/VG1819#421] opened 2019-04-04 00:41 UTC
Caused game out of sync

**Comment by kamarapala** [comment] 2019-04-05 16:46
Extra details:
- This issue is caused by the Summon ability, but can only occur if you use the ability the same turn the Witch is first summoned
- The issue is that when a unit is added to the IT, it's added to m_waitUnitObjectList and the list is sorted. 
  - In the scenario of this issue, if you use the Witch's Summon the same turn she was summoned, the Servant is added to m_waitUnitObjectList and it is sorted.
  - Summoning Witch has an IN of 4 and Servant has an IN of 6, so when the list is sorted after the Servant is added into the wait list, he ends up ahead of the Witch, but it is still the Witch's turn. 
Ex.
![image](https://user-images.githubusercontent.com/31244529/55642887-16ca7500-57a8-11e9-932e-1f3dfeb1d422.png)
    - In this example, you can see that the Witch has used Summon and that the red indicator shows that it's still the Witch's turn, but the Servant is ahead of the Witch in the IT

- This results in a desync as the sync checks the unit at the front of the InitiativeTracker, which should have been the Witch, but it's the Servant.
- If you allow a full game turn to pass before using the Witch's summon, the issue will not occur as she will be in the m_unitObjectList and the summoned Servants will be added to the m_waitUnitObjectList

**Comment by kamarapala** [comment] 2019-04-05 16:49
@SRJYC I'll be leaving this for you to handle as I think it is better for you to decide the solution for this as it is about the InitiativeTracker

**Closed** 2019-04-06 00:04 UTC
